services:
  server:
    build:
      context: ./server
    depends_on:
      - todo-database
    ports:
      - 3001:3001
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
    depends_on:
      - server
    ports:
      - 5173:5173

  todo-database:
    image: mongo:6
    ports:
      - 27018:27017
